### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by hellogiiiiit** [oxywen/Python_Face_Login#2]
你好，我在尝试注册的时候出现以下的错误：
Internal Server Error: /user/register/
Traceback (most recent call last):
  File "D:\Python-3.6.1\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python-3.6.1\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: hubu_users.sex

**Comment by zhixia11** [comment]
看起来似乎是数据表出现了问题，查看数据库建表语句，是否把性别字段设置了非空约束。或修改代码，注册用户时默认给一个默认性别

**Comment by hellogiiiiit** [comment]
> 看起来似乎是数据表出现了问题，查看数据库建表语句，是否把性别字段设置了非空约束。或修改代码，注册用户时默认给一个默认性别

好的，我已解决

**Comment by hellogiiiiit** [comment]
> 看起来似乎是数据表出现了问题，查看数据库建表语句，是否把性别字段设置了非空约束。或修改代码，注册用户时默认给一个默认性别

可以加一下我的qq吗？1343330618，有些问题想问您，或者您给我留个联系方式，我加你，感谢！！
